frontend:
  image:
    repository: januszkujawa84/backstage-frontend
    tag: base
  containerPort: 3000

backend:
  enabled: true
  demoData: true
  image:
    repository: januszkujawa84/backstage-backend
    tag: base
  containerPort: 7007
  
lighthouse:
  enabled: true

nameOverride: ''
fullnameOverride: ''

issuer:
  email: 'test@example.com'
  clusterIssuer: 'selfsigned-cluster-issuer'

postgresql:
  enabled: true
  
appConfig:
  app:
    baseUrl: https://backstage.172.25.0.3.nip.io
    title: Backstage Dev
    googleAnalyticsTrackingId:
  backend:
    baseUrl: https://backstage.172.25.0.3.nip.io
    listen:
      port: 7007
    cors:
      origin: https://backstage.172.25.0.3.nip.io
    database:
      client: pg
      connection:
        database: backstage_plugin_catalog
        host:
        user:
        port:
        password:
        ssl:
          rejectUnauthorized: false
          ca:
  sentry:
    organization: backstage-base
  techdocs:
    storageUrl: https://backstage.172.25.0.3.nip.io/api/techdocs/static/docs
    requestUrl: https://backstage.172.25.0.3.nip.io/api/techdocs
  lighthouse:
    baseUrl: https://backstage.172.25.0.3.nip.io/lighthouse-api
  rollbar:
    organization: backstage-base


auth:
  github:
    clientId: 
    clientSecret: 
  githubToken: 