frontend:
  image:
    repository: januszkujawa84/backstage-frontend
    tag: test
  containerPort: 3000

backend:
  enabled: true
  demoData: true
  image:
    repository: januszkujawa84/backstage-backend
    tag: test
  containerPort: 7007
  
lighthouse:
  enabled: true

nameOverride: ''
fullnameOverride: 'backstage'

issuer:
  email: 'test@example.com'
  clusterIssuer: 'selfsigned-cluster-issuer'

postgresql:
  enabled: true
  service:
    port: 5432

global:
  postgresql:
    postgresqlUsername: postgres
    caFilename: ca.crt
  nodeSelector: {}
  
appConfig:
  app:
    baseUrl: https://backstage.172.25.0.3.nip.io
    title: Backstage Dev
    ghorg: devopsapp84
    googleAnalyticsTrackingId:
  backend:
    baseUrl: https://backstage.172.25.0.3.nip.io
    listen:
      port: 7007
    cors:
      origin: https://backstage.172.25.0.3.nip.io
    database:
      client: pg
      connection:
        database: backstage_plugin_catalog
        host: backstage-postgresql
        user: backstage
        port: 5432
        password: init1234
        ssl:
          rejectUnauthorized: false
          ca:
  sentry:
    organization: backstage-dev
  techdocs:
    storageUrl: https://backstage.172.25.0.3.nip.io/api/techdocs/static/docs
    requestUrl: https://backstage.172.25.0.3.nip.io/api/techdocs
  lighthouse:
    baseUrl: https://backstage.172.25.0.3.nip.io/lighthouse-api
  rollbar:
    organization: backstage-dev


auth:
  github:
    clientId: 
    clientSecret: 
  githubToken:  